// Per-transformer tests live next to their implementation in ./transformer/ and are re-exported
// here so they run under this (registered) module.
export * from './transformer/core.test.js'
export * from './transformer/id.test.js'
export * from './transformer/rename.test.js'
export * from './transformer/conform.test.js'
export * from './transformer/pipe.test.js'
export * from './transformer/attr.test.js'
export * from './transformer/value.test.js'
export * from './transformer/rename-attrs.test.js'
export * from './transformer/attribution-to-format.test.js'
export * from './transformer/full-attributions.test.js'
export * from './transformer/project.test.js'
export * from './transformer/inline.test.js'
export * from './transformer/children.test.js'
export * from './transformer/marks.test.js'
